name: Sheenam Build Pipeline
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master  
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Check Out code
      uses: actions/checkout@v2
    - name: Setup .NET 10.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 10.0
        include-prerelease: false
    - name: Restore Nuget Packages
      run: dotnet restore
    - name: Build the project
      run: dotnet build --no-restore
    - name: Run Unit Tests
      run: dotnet test --no-build --verbosity normal
